const ActionTypes = {
  REGISTER_USERS: 'REGISTER_USERS',
  SET_AUTH_USER: 'SET_AUTH_USER',
  UNSET_AUTH_USER: 'UNSET_AUTH_USER',
  SET_IS_PRELOAD: 'SET_IS_PRELOAD',
  RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
  RECEIVE_MY_PRODUCTS: 'RECEIVE_MY_PRODUCTS',
  RECEIVE_DETAIL_PRODUCT: 'RECEIVE_DETAIL_PRODUCT',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
};

export default ActionTypes;
